=== cumm0099/Simple-Static-Website/distinctions.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT Distinctions ANY>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type (work|cell) #REQUIRED>
<!ATTLIST phone primary (primary) #IMPLIED>
<!ELEMENT email (#PCDATA)>

<!ELEMENT Distinction (Name, description, phone+, email?)>

=== cumm0099/Simple-Static-Website/distinctions.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Distinctions SYSTEM "distinctions.dtd">

<Distinctions>
	<Distinction>
		<Name>Rick Chubb</Name>
		<description>School District</description>
		<phone type="work" primary="primary">(763)767-1804</phone>
		<phone type="cell">(612) 290-5579</phone>
		<email>randdchubb@aol.com</email>
	</Distinction>

	<Distinction>
		<Name>Rick Chubb</Name>
		<description>Potential Employee</description>
		<phone type="work" primary="primary">(763)767-1804</phone>
		<phone type="cell">(612) 290-5579</phone>
		<email>randdchubb@aol.com</email>
	</Distinction>

	<Distinction>
		<Name>Doris Chubb</Name>
		<description> Current Drivers</description>
		<phone type="work" primary="primary">(763)767-1804</phone>
		<phone type="cell">(612) 290-5577</phone>
		<email>dorischubb@yahoo.com</email>
	</Distinction>

	<Distinction>
		<Name>Doris or Rick Chubb</Name>
		<description>New Clients</description>
		<phone type="work" primary="primary">(763)767-1804</phone>
		<email>randdchubb@aol.com</email>
	</Distinction>

</Distinctions>
